#  SGC
#    Command:
#        conda activate grist2
#        cd ~/phage_affix/fancy_phage/spacegraphcats/
#        python -m spacegraphcats run config_sgc.yml extract_contigs extract_reads --nolock
#    srun:
#        srun -p bmm -J sgc -t 6:00:00 --mem=70gb -c 2 --pty bash


catlas_base: 'SM_CTTKX'
input_sequences:
#- ~/phage_affix/fancy_phage/grist/outputs.gather_virome/trim/SM_CTTKX.trim.fq.gz
- ../grist/outputs.gather_virome/trim/SM_CTTKX.trim.fq.gz
ksize: 21
radius: 1
#experiment: fancy_phage_1

search:
- ../data/ref_genomes/ivig_358.fa
- ../data/ref_genomes/uvig_505586.fa
- ../data/ref_genomes/uvig_264832.fa
- ../data/ref_genomes/uvig_225190.fa
- ../data/ref_genomes/uvig_308517.fa
- ../data/ref_genomes/uvig_389464.fa
- ../data/ref_genomes/uvig_360436.fa
- ../data/ref_genomes/uvig_110493.fa
- ../data/ref_genomes/uvig_52126.fa
- ../data/ref_genomes/uvig_245649.fa
- ../data/ref_genomes/uvig_516991.fa
- ../data/ref_genomes/uvig_219649.fa
- ../data/ref_genomes/uvig_143949.fa
- ../data/ref_genomes/uvig_96206.fa
- ../data/ref_genomes/uvig_221329.fa