---
title: "five_phage"
author: "Hannah E. Houts"
date: "`r Sys.Date()`"
output: html_document
---


## load libs
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(viridisLite)
#library(gridExtra)
library(ggpubr)
options(scipen = 999)
```



## load data
```{r}
duos_og <- read_csv("Desktop/duos.csv", show_col_types = FALSE)
duos <- duos_og
duos <- unite(duos, duo, c("pr","hr"), sep = "_", remove = FALSE, na.rm = FALSE)
```





## some plots, pre pivot 

### shared hashes
```{r}
duos %>% 
#
#  
  ggplot(aes(x=duo, y = pr_pn_sh_hshs, fill = pr)) + geom_col()+
#  facet_wrap(~pr)+
#
#
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_fill_viridis_d(option = "D") +
  labs(title = "Shared Hashes",
      x = "duo",
      y= "number of shared hashes",
      fill= "Phage Reference Genome")+
  coord_flip()
```

### containment
```{r, warning=FALSE}
#################################### p REF in h REF
plot_pr_in_hr <- duos %>% 
#
#  
  ggplot(aes(x=duo, y = cmt_pr_in_hr, fill = pr)) + geom_col()+
  geom_text(aes(label = round(cmt_pr_in_hr, digits = 4)), hjust = -1)+
#
#
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ylim(0, 0.5)+
  scale_fill_viridis_d(option = "D") +
  labs(title = "p REF in h REF",
      x = "duo",
      y= "containment",
      fill= "Phage Reference Genome")+
  coord_flip()
plot_pr_in_hr


#################################### p NBHD in h REF
plot_pn_in_hr <- duos %>% 
#
#  
  ggplot(aes(x=duo, y = cmt_pn_in_hr, fill = pr)) + geom_col()+
  geom_text(aes(label = round(cmt_pn_in_hr, digits = 4)), hjust = -1)+
#
#
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ylim(0, 0.5)+
  scale_fill_viridis_d(option = "D") +
  labs(title = "p NBHD in h REF",
      x = "duo",
      y= "containment",
      fill= "Phage Reference Genome")+
  coord_flip()
plot_pn_in_hr


#################################### p NBHD in h NBHD
plot_pn_in_hn <- duos %>% 
#
#  
  ggplot(aes(x=duo, y = cmt_pn_in_hn, fill = pr)) + geom_col()+
  geom_text(aes(label = round(cmt_pn_in_hn, digits = 4)), hjust = -1)+
#
#
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ylim(0, 0.5)+
  scale_fill_viridis_d(option = "D") +
  labs(title = "p NBHD in h NBHD",
      x = "duo",
      y= "containment",
      fill= "Phage Reference Genome")+
  coord_flip()
plot_pn_in_hn


#################################### p REF in h NBHD
plot_pr_in_hn <- duos %>% 
#
#  
  ggplot(aes(x=duo, y = cmt_pr_in_hn, fill = pr)) + geom_col()+ 
  geom_text(aes(label = round(cmt_pr_in_hn, digits = 4)), hjust = -1)+
#
#
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ylim(0, 0.5)+
  scale_fill_viridis_d(option = "D") +
  labs(title = "p REF in h NBHD",
      x = "duo",
      y= "containment",
      fill= "Phage Reference Genome")+
  coord_flip()
plot_pr_in_hn
```
 Note: look at pRef in hRef, then pN in hRef - 
  most go down, but one duo, uvig_409809_GCA_003470775, slightly rises.
Meaning 


```{r}

p1 <- plot_pr_in_hr
p2 <- plot_pn_in_hr
p3 <- plot_pn_in_hn
p4 <- plot_pr_in_hn

ggsave(plot_pr_in_hr, 
       plot = plot_pr_in_hr, device = NULL, path = "~/projects/dynamic-duos/sgc_containment_figs/")

ggsave(plot_pn_in_hr, 
       plot = plot_pn_in_hr,
       device = NULL,
       path = "~/projects/dynamic-duos/sgc_containment_figs/")

ggsave(plot_pn_in_hn, 
       plot = plot_pn_in_hn, 
       device = NULL,
       path = "~/projects/dynamic-duos/sgc_containment_figs/")

ggsave(plot_pr_in_hn, 
       plot = plot_pr_in_hn, 
       device = NULL,
       path = "~/projects/dynamic-duos/sgc_containment_figs/")

#ggsave(
#  plot_pr_in_hr,
#  plot = plot_pr_in_hr,
#  device = NULL,
#  path = "~/projects/dynamic-duos/",
#  scale = 1,
#  width = NA,
#  height = NA,
#  units = c("in", "cm", "mm", "px"),
#  dpi = 300,
#  limitsize = TRUE,
#  bg = NULL,
#)
```


## combo plot (none of this works lol)
```{r}

p1 <- plot_pr_in_hr
p2 <- plot_pn_in_hr
p3 <- plot_pn_in_hn
p4 <- plot_pr_in_hn

grid.arrange(p1, p2, p3, p4, ncol = 4, nrow = 1, respect=TRUE)


p1
p2
p3
p4


ggarrange(p1, p2, p3, p4, ncol = 1, nrow = 4)grid.arrange(p, p, respect=TRUE, heights=c(1,2)) # relative heights





pushViewport(viewport(layout = grid.layout(2, 2)))
vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)
print(p1, vp = vplayout(1, 1:2))
print(p2, vp = vplayout(2, 1))
print(p3, vp = vplayout(2, 2))

#grid.newpage()
#grid.draw(g)



```

## Observations

- why is 
## Chuck

```{r}
duos

```
```{r}
tabyl(duos$cmt_hr_in_pr)

summarise(duos %>% 
  group_by(pr,hr)
  )
```

