#    ███████╗    ███╗   ██╗     █████╗     ██╗  ██╗    ███████╗    ███████╗    ██╗    ██╗     ███████╗    
#    ██╔════╝    ████╗  ██║    ██╔══██╗    ██║ ██╔╝    ██╔════╝    ██╔════╝    ██║    ██║     ██╔════╝    
#    ███████╗    ██╔██╗ ██║    ███████║    █████╔╝     █████╗      █████╗      ██║    ██║     █████╗      
#    ╚════██║    ██║╚██╗██║    ██╔══██║    ██╔═██╗     ██╔══╝      ██╔══╝      ██║    ██║     ██╔══╝      
#    ███████║    ██║ ╚████║    ██║  ██║    ██║  ██╗    ███████╗    ██║         ██║    ███████╗███████╗    
#    ╚══════╝    ╚═╝  ╚═══╝    ╚═╝  ╚═╝    ╚═╝  ╚═╝    ╚══════╝    ╚═╝         ╚═╝    ╚══════╝╚══════╝    
#                                                                                                         
#    ████████████████████████████████████████████████████████████████████████████████████████████████████



#    █ █ █ Globs and Libs █ █ █ 
PHAGES = ['ivig_358', 'uvig_505586', 'uvig_264832', 'uvig_225190', 'uvig_308517', 'uvig_389464', 'uvig_360436', 'uvig_110493', 'uvig_52126', 'uvig_245649', 'uvig_516991', 'uvig_219649', 'uvig_143949', 'uvig_96206', 'uvig_221329']
#from sourmash import load_one_signature
#import pandas as pd
#import os


#    ████████████████████████████████████████████████████████████████████████████████████████████████████

#     █████╗     ██╗         ██╗     
#    ██╔══██╗    ██║         ██║     
#    ███████║    ██║         ██║     
#    ██╔══██║    ██║         ██║     
#    ██║  ██║    ███████╗    ███████╗
#    ╚═╝  ╚═╝    ╚══════╝    ╚══════╝


rule all: 
    input:
#       █ █ █ get_phage_ref_genomes █ █ █
#     expand("data/ref_genomes/{phage}.fa", phage=PHAGES),
#       █ █ █ make_catlas █ █ █
#        "spacegraphcats/SM_CTTKX_k21_r1/catlas.csv",
#       █ █ █ make_nbhds █ █ █ 
#        expand("spacegraphcats/SM_CTTKX_k21_r1_search_oh0/{phage}.fa.cdbg_ids.contigs.fa.gz", phage=PHAGES)
#        █ █ █ rule sketch_phage_nbhds_sigs █ █ █ 
        expand("sigs/{phage}.SM_CTTKX_k21.fa.cdbg_ids.reads.sig", phage = PHAGES)



#    ████████████████████████████████████████████████████████████████████████████████████████████████████
#    
#    ██████╗     ██╗   ██╗    ██╗         ███████╗    ███████╗
#    ██╔══██╗    ██║   ██║    ██║         ██╔════╝    ██╔════╝
#    ██████╔╝    ██║   ██║    ██║         █████╗      ███████╗
#    ██╔══██╗    ██║   ██║    ██║         ██╔══╝      ╚════██║
#    ██║  ██║    ╚██████╔╝    ███████╗    ███████╗    ███████║
#    ╚═╝  ╚═╝     ╚═════╝     ╚══════╝    ╚══════╝    ╚══════╝
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
rule get_phage_ref_genomes:
    input:
        gutphagedatabase="/group/ctbrowngrp/virus-references/gut-phage-db/GPD_sequences.fa.gz"
    output: 
        phage_genome="data/ref_genomes/{phage}.fa"
    shell:
        """
        zgrep -A1 '{wildcards.phage}' {input.gutphagedatabase} > {output.phage_genome}
        """

#    ════════════════════════════════════════════════════════════════════════════════════════════════════
rule make_catlas:
    input:
        phage_genome = expand("data/ref_genomes/{phage}.fa", phage=PHAGES),
        sgc_config = "spacegraphcats/config_sgc.yml"
    output: 
        catlas = "spacegraphcats/SM_CTTKX_k21_r1/catlas.csv"
    shell:
        """
        cd spacegraphcats/
        python -m spacegraphcats run config_sgc.yml build --nolock
        cd ..
        """
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
rule make_nbhds:
    input:
        catlas = "spacegraphcats/SM_CTTKX_k21_r1/catlas.csv",
        phage_genome = expand("data/ref_genomes/{phage}.fa", phage=PHAGES),
        sgc_config = ancient("spacegraphcats/config_sgc.yml"),

    output: 
        nbhds = "spacegraphcats/SM_CTTKX_k21_r1_search_oh0/{phage}.fa.cdbg_ids.contigs.fa.gz"
    shell:
        """
        cd spacegraphcats/
        python -m spacegraphcats run config_sgc.yml extract_contigs extract_reads --nolock
        cd ..
        """
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
rule sketch_phage_nbhd_sigs:
    input:
        "spacegraphcats/SM_CTTKX_k21_r1_search_oh0/{phage}.fa.cdbg_ids.reads.gz"

    output:
        "sigs/{phage}.SM_CTTKX_k21.fa.cdbg_ids.reads.sig"
        
    shell:
        """
        sourmash sketch dna -p k=21,scaled=1 {input} -o {output} 
        """
#    ════════════════════════════════════════════════════════════════════════════════════════════════════
rule sketch_phage_ref_sigs:
    input:
        "data/ref_genomes/{phage}.fa.cdbg_ids.reads.gz"

    output:
        "sigs/{phage}.SM_CTTKX_k21.fa.cdbg_ids.reads.sig"
        
    shell:
        """
        sourmash sketch dna -p k=21,scaled=1 {input} -o {output} 
        """
#    ════════════════════════════════════════════════════════════════════════════════════════════════════

#    ════════════════════════════════════════════════════════════════════════════════════════════════════

#    ════════════════════════════════════════════════════════════════════════════════════════════════════

#    ════════════════════════════════════════════════════════════════════════════════════════════════════


